reloc: install build==0.10.0
to silence the warning from pip:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.5.1 requires build<0.11.0,>=0.10.0, but you have build 1.0.3 which is incompatible.
```

unfortunately, despite that poetry master HEAD now supports
build==1.0.3, the latest release of poetry (v1.6.1) still does
not include that change. so let's use the version supported by
poetry.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>