client side describe was calling `describe_keyspaces` wrongly
seem like in 9ccfa7e29d1372262c2980d78fb35e22b85e039a by mistake
we were calling `describe_keyspaces` and not `describe_keyspaces_client`

hence casuing the following error:
```
cqlsh> DESCRIBE KEYSPACES
Shell.describe_keyspaces() missing 1 required positional argument: 'rows'
```